# Generated by Django 3.2.3 on 2021-06-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adresse',
        ),
    ]
